language: php

php:
  - 5.6
  - 7.0
  - 7.1

install:
  - composer install
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover="build/logs/clover.xml" Tests
  - vendor/bin/phpcs --standard=PSR2 Source

after_success:
  - php vendor/bin/coveralls -v