language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

install:
  - composer install
  - composer require satooshi/php-coveralls

before_script:
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover="build/logs/clover.xml" Tests
  - vendor/bin/phpcs --standard=PSR12 Source Tests

after_success:
  - php vendor/bin/coveralls -v