on:
  - push
  - pull_request:
    types: [opened, synchronize, reopened]
name: Main Workflow
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Run tests
        run: |
          composer install
          vendor/bin/phpunit --coverage-clover="build/logs/clover.xml" Tests
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=fresh-advance
            -Dsonar.projectKey=Fresh-Advance_regex-dependency
            -Dsonar.projectName=RegexDependency
            -Dsonar.projectVersion=0.3
            -Dsonar.sources=Source
            -Dsonar.tests=Tests
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.php.coverage.reportPaths=build/logs/clover.xml
            -Dsonar.php.tests.reportPath=build/logs/phpunit.xml